#pragma once

// Source: https://github.com/vipersaudio/viperfx_core_binary/blob/master/viperfx_intf.h
// Updated parameters source: https://github.com/vipersaudio/viper4android_fx/blob/master/android_4.x/src/com/vipercn/viper4android_v2/service/ViPER4AndroidService.java

typedef enum {
    PARAM_GET_ENABLED = 0,
    PARAM_GET_FRAME_COUNT,
    PARAM_GET_VERSION,
    PARAM_GET_DISABLE_REASON,
    PARAM_GET_CONFIG,
    PARAM_GET_ARCHITECTURE,
} param_get_t;

typedef enum {
    PARAM_SET_RESET = 0,
    PARAM_SET_DDC_ENABLE,
    PARAM_SET_DDC_COEFFICIENTS,
    PARAM_SET_VIPER_BASS_ENABLE,
    PARAM_SET_VIPER_BASS_MODE,
    PARAM_SET_VIPER_BASS_FREQUENCY,
    PARAM_SET_VIPER_BASS_GAIN,
    PARAM_SET_VIPER_CLARITY_ENABLE,
    PARAM_SET_VIPER_CLARITY_MODE,
    PARAM_SET_VIPER_CLARITY_GAIN,
    PARAM_SET_OUTPUT_GAIN,
    PARAM_SET_THRESHOLD_LIMIT,
    PARAM_SET_SPEAKER_OPTIMIZATION_ENABLE,
    PARAM_SET_ANALOGX_ENABLE,
    PARAM_SET_ANALOGX_LEVEL,
    PARAM_SET_TUBE_SIMULATOR_ENABLE,
    PARAM_SET_CURE_ENABLE,
    PARAM_SET_CURE_LEVEL,
    PARAM_SET_REVERBERATION_ENABLE,
    PARAM_SET_REVERBERATION_ROOM_SIZE,
    PARAM_SET_REVERBERATION_SOUND_FIELD,
    PARAM_SET_REVERBERATION_DAMPING,
    PARAM_SET_REVERBERATION_WET_SIGNAL,
    PARAM_SET_REVERBERATION_DRY_SIGNAL,
    PARAM_SET_DIFFERENTIAL_SURROUND_ENABLE,
    PARAM_SET_DIFFERENTIAL_SURROUND_DELAY,
    PARAM_SET_FIELD_SURROUND_ENABLE,
    PARAM_SET_FIELD_SURROUND_DEPTH,
    PARAM_SET_FIELD_SURROUND_MID_IMAGE,
    PARAM_SET_IIR_EQUALIZER_ENABLE,
    PARAM_SET_IIR_EQUALIZER_BAND_LEVEL,
} param_set_t;
