name: Package Magisk Module

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Download the compiled binaries from the 'build' workflow
      - name: Download compiled libraries
        uses: actions/download-artifact@v3
        with:
          name: compiled-binaries
          path: compiled/

      # Prepare Magisk module directory by copying the necessary ABI files
      - name: Prepare Magisk Module
        run: |
          for abi in armeabi-v7a arm64-v8a x86 x86_64; do
            mkdir -p module/common/files/$abi
            cp compiled/libv4a_re_$abi.so module/common/files/$abi/
          done

      # Zip the Magisk module
      - name: Zip Magisk Module
        run: |
          cd module
          zip -r ../magisk_module.zip ./

      # Upload the zipped Magisk module as an artifact
      - name: Upload Magisk Module
        uses: actions/upload-artifact@v3
        with:
          name: magisk_module
          path: magisk_module.zip
